import React, { useState, useEffect } from 'react';
import { useSelector } from 'react-redux';
import { calculateWeeklyStressMetrics, getStressLevel } from '../utils/stressAnalysis';
import DepartmentSelector from '../components/DepartmentSelector';
import StressChart from '../components/StressChart';
import { FiTrendingUp, FiDownload, FiAlertTriangle, FiCheckCircle } from 'react-icons/fi';
import '../styles/analysis-page.css';

const AnalysisPage = () => {
  const { selectedDepartment, selectedSemester, timetables } = useSelector(
    (state) => state.timetables
  );
  const [selectedTimetableId, setSelectedTimetableId] = useState(null);
  const [chartType, setChartType] = useState('bar');

  const relevantTimetables = timetables.filter(
    (t) => t.department === selectedDepartment && t.semester === selectedSemester
  );

  // Reset selected option whenever the filtered set changes
  useEffect(() => {
    if (relevantTimetables.length > 0) {
      // Find currently selected ID, or default to first if invalid
      const stillExists = relevantTimetables.find((t) => t.id === selectedTimetableId);
      if (!stillExists) {
        setSelectedTimetableId(relevantTimetables[0].id);
      }
    } else {
      setSelectedTimetableId(null);
    }
  }, [selectedDepartment, selectedSemester, relevantTimetables]);

  const hasTimetables = relevantTimetables.length > 0;

  const selectedTimetable = hasTimetables
    ? (relevantTimetables.find((t) => t.id === selectedTimetableId) ??
        relevantTimetables[0])
    : null;

  const metrics = selectedTimetable
    ? calculateWeeklyStressMetrics(selectedTimetable.entries)
    : null;

  const dayChartData = metrics
    ? Object.entries(metrics.dayStressScores).map(([day, score]) => ({
        name: day.slice(0, 3), // 'Mon', 'Tue', etc.
        fullName: day,
        value: Math.round(score),
      }))
    : [];

  // Handle generating and downloading the stress report
  const handleDownloadReport = () => {
    if (!selectedTimetable || !metrics) return;

    const stressLevel = getStressLevel(metrics.averageStress);
    const lines = [
      '╔══════════════════════════════════════════════════════════╗',
      '║          SMART TIMETABLE — STRESS ANALYSIS REPORT        ║',
      '╚══════════════════════════════════════════════════════════╝',
      '',
      `Department   : ${selectedDepartment}`,
      `Semester     : ${selectedSemester}`,
      `Option       : ${relevantTimetables.findIndex(t => t.id === selectedTimetable.id) + 1}`,
      `Generated At : ${new Date().toLocaleString()}`,
      '',
      '──────────────────────────────────────────────────────────',
      '  OVERALL STRESS SUMMARY',
      '──────────────────────────────────────────────────────────',
      `  Average Weekly Stress : ${metrics.averageStress.toFixed(1)}/100  (${stressLevel.label})`,
      `  Optimization Score    : ${selectedTimetable.optimizationScore.toFixed(1)}%`,
      `  Total Lectures        : ${selectedTimetable.entries.length}`,
      '',
      '──────────────────────────────────────────────────────────',
      '  DAILY STRESS PATTERN',
      '──────────────────────────────────────────────────────────',
      ...Object.entries(metrics.dayStressScores).map(([day, score]) => {
        const lvl = getStressLevel(score);
        const bar = '█'.repeat(Math.round(score / 5)).padEnd(20, '░');
        return `  ${day.padEnd(12)} ${bar}  ${Math.round(score)}/100  [${lvl.label}]`;
      }),
      '',
      '──────────────────────────────────────────────────────────',
      '  DAY-BY-DAY BREAKDOWN',
      '──────────────────────────────────────────────────────────',
      ...Object.entries(metrics.dayMetrics).map(([day, m]) => {
        const score = metrics.dayStressScores[day];
        const lvl = getStressLevel(score);
        return [
          `  ${day}`,
          `    Total Lectures    : ${m.totalLectures}`,
          `    Hard Subjects     : ${m.hardSubjects}`,
          `    Gaps Between      : ${m.gapsBetweenLectures}`,
          `    Stress Score      : ${Math.round(score)}/100 (${lvl.label})`,
          '',
        ].join('\n');
      }),
      '──────────────────────────────────────────────────────────',
      '  WARNINGS',
      '──────────────────────────────────────────────────────────',
      ...(metrics.warnings.length === 0
        ? ['  ✅ No warnings — timetable looks well-balanced!']
        : metrics.warnings.map((w) => `  ⚠️  [${w.severity.toUpperCase()}] ${w.message}`)),
      '',
      '══════════════════════════════════════════════════════════',
      '  Generated by Smart Timetable System',
      '══════════════════════════════════════════════════════════',
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `stress-report-${selectedDepartment}-sem${selectedSemester}-opt${relevantTimetables.findIndex(t => t.id === selectedTimetable.id) + 1}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="analysis-page page-content">
      <div className="page-header">
        <h1>Stress Analysis</h1>
        <p>Detailed timetable stress metrics and optimization insights</p>
      </div>

      <DepartmentSelector />

      {!hasTimetables ? (
        <div className="empty-state card">
          <div className="empty-icon">📉</div>
          <h3>No Data to Analyze</h3>
          <p>
            Generate a timetable from the <strong>Generator</strong> page first,
            then come back here to see stress analysis.
          </p>
        </div>
      ) : (
        <>
          {/* Option selector */}
          <div className="option-selector card">
            <div className="option-selector-header">
              <h3>Select Timetable Option</h3>
              <button
                id="download-report-btn"
                className="btn-report"
                onClick={handleDownloadReport}
                title="Download stress report"
              >
                <FiDownload size={16} />
                Download Report
              </button>
            </div>
            <div className="button-group">
              {relevantTimetables.map((opt, idx) => (
                <button
                  key={opt.id}
                  className={`option-btn ${selectedTimetableId === opt.id ? 'active' : ''}`}
                  onClick={() => setSelectedTimetableId(opt.id)}
                >
                  Option {idx + 1}
                  <span className="score-badge">
                    {opt.optimizationScore.toFixed(1)}%
                  </span>
                </button>
              ))}
            </div>
          </div>

          <div className="analysis-grid">
            {/* Overall Stress Summary */}
            <div className="stress-summary card">
              <h3>
                <FiTrendingUp size={20} />
                Overall Stress Summary
              </h3>
              <div className="summary-metrics">
                <div className="metric">
                  <span className="metric-label">Average Weekly Stress</span>
                  <span className="metric-value">
                    {metrics.averageStress.toFixed(1)}/100
                  </span>
                  <span
                    className={`metric-level ${getStressLevel(
                      metrics.averageStress
                    ).label.toLowerCase()}`}
                  >
                    {getStressLevel(metrics.averageStress).label}
                  </span>
                </div>

                <div className="metric">
                  <span className="metric-label">Optimization Score</span>
                  <span className="metric-value" style={{ color: '#a3e635' }}>
                    {selectedTimetable.optimizationScore.toFixed(1)}%
                  </span>
                </div>

                <div className="metric">
                  <span className="metric-label">Total Lectures</span>
                  <span className="metric-value">
                    {selectedTimetable.entries.length}
                  </span>
                </div>

                {/* Stress distribution mini-bar */}
                <div className="metric" style={{ borderBottom: 'none', paddingBottom: 0 }}>
                  <span className="metric-label">Stress Distribution</span>
                  <div className="stress-distribution">
                    {Object.entries(metrics.dayStressScores).map(([day, score]) => {
                      const lvl = getStressLevel(score);
                      return (
                        <div key={day} className="dist-bar-wrap" title={`${day}: ${Math.round(score)}/100`}>
                          <div
                            className="dist-bar"
                            style={{
                              height: `${Math.max(8, score)}%`,
                              backgroundColor: lvl.color,
                            }}
                          />
                          <span className="dist-day">{day.slice(0, 3)}</span>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            </div>

            {/* Daily Stress Chart */}
            <div className="stress-chart card">
              <div className="chart-header">
                <h3>Daily Stress Pattern</h3>
                <div className="chart-type-toggle">
                  <button
                    className={`chart-toggle-btn ${chartType === 'bar' ? 'active' : ''}`}
                    onClick={() => setChartType('bar')}
                  >
                    Bar
                  </button>
                  <button
                    className={`chart-toggle-btn ${chartType === 'line' ? 'active' : ''}`}
                    onClick={() => setChartType('line')}
                  >
                    Line
                  </button>
                </div>
              </div>
              <StressChart data={dayChartData} type={chartType} />
              <div className="chart-legend">
                <span className="legend-dot" style={{ background: '#10b981' }} /> Low (≤30)
                <span className="legend-dot" style={{ background: '#f59e0b' }} /> Medium (≤60)
                <span className="legend-dot" style={{ background: '#ef4444' }} /> High (≤85)
                <span className="legend-dot" style={{ background: '#7c3aed' }} /> Critical
              </div>
            </div>
          </div>

          {/* Warnings */}
          {metrics.warnings.length > 0 ? (
            <div className="warnings-section">
              <h3>⚠️ Warnings ({metrics.warnings.length})</h3>
              <div className="warnings-list">
                {metrics.warnings.map((w, i) => (
                  <div key={i} className={`warning-item ${w.severity}`}>
                    <span className="warning-icon">
                      <FiAlertTriangle />
                    </span>
                    <div className="warning-content">
                      <h4>{w.day} — {w.type.replace('_', ' ')}</h4>
                      <p>{w.message}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="success-message">
              <FiCheckCircle size={40} />
              <h3>Well Balanced Timetable!</h3>
              <p>No stress warnings detected for this timetable option.</p>
            </div>
          )}

          {/* Day-by-Day Breakdown */}
          <div className="detailed-analysis">
            <h3>Day-by-Day Breakdown</h3>
            <div className="day-cards-grid">
              {Object.entries(metrics.dayMetrics).map(([day, dayMetrics]) => {
                const stress = metrics.dayStressScores[day];
                const stressLevel = getStressLevel(stress);
                return (
                  <div key={day} className="day-card card">
                    <div className="day-header">
                      <h4>{day}</h4>
                      <div
                        className={`stress-badge ${stressLevel.label.toLowerCase()}`}
                      >
                        {Math.round(stress)}/100
                      </div>
                    </div>
                    {/* Stress progress bar */}
                    <div className="stress-progress-bar">
                      <div
                        className="stress-progress-fill"
                        style={{
                          width: `${stress}%`,
                          backgroundColor: stressLevel.color,
                        }}
                      />
                    </div>
                    <div className="day-metrics">
                      <div className="metric-row">
                        <span className="metric-name">📚 Total Lectures</span>
                        <span className="metric-num">
                          {dayMetrics.totalLectures}
                        </span>
                      </div>
                      <div className="metric-row">
                        <span className="metric-name">⚠️ Hard Subjects</span>
                        <span className="metric-num">
                          {dayMetrics.hardSubjects}
                        </span>
                      </div>
                      <div className="metric-row">
                        <span className="metric-name">⏱️ Gaps Between</span>
                        <span className="metric-num">
                          {dayMetrics.gapsBetweenLectures}
                        </span>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </>
      )}
    </div>
  );
};

export default AnalysisPage;
